spring.application.name=current-percentage-service
server.port=8084
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=energy
spring.rabbitmq.password=energy123
spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=energy
spring.datasource.password=energy123
spring.jpa.hibernate.ddl-auto=none