spring.application.name=energy-api
spring.datasource.url=jdbc:postgresql://localhost:5432/energydb
spring.datasource.username=energy
spring.datasource.password=energy123
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration